### PR TITLE
#1 Change 5MB sized png fieldtest Assen photo to lightweight jpg

### PR DESCRIPTION
**Pull request by kkoenen**
Changed photo from .png to .jpg, resized to 1828x914. Size 548.202 bytes. Closing issue #1.

### CODE REVIEW

**Comment by bwbroersma** [comment]
@kkoenen commits have to be GPG signed, see the [Pull Request Checklist](https://github.com/minvws/.github/blob/47745f5318f47cb54bf99f562f5366e4c87143c7/CONTRIBUTING.md#pull-request-checklist). You can do a [web trick workaround](https://github.com/minvws/nl-covid19-notification-app-dashboard/pull/3#issuecomment-635341616) to sign with GitHub's key or rebase with `git filter-branch`. But since in this case it's just one commit, you can just use `git commit --amend -S --no-edit`.

**Review by emartynov — APPROVED** [review]

**Review by dirkx — APPROVED** [review]
Splendig. Thanks. Make sure your commit is signed (rebase if needed).

**Comment by JolandaVerhoef** [comment]
The original commit hasn't been verified, which means we can't merge this pull request. @kkoenen can you please update? Otherwise I'll close this PR in a couple of days because it has been stale for a long time.

**Comment by bwbroersma** [comment]
> The original commit hasn't been verified, which means we can't merge this pull request.

A few other options:
1. Remove the signing restrictions, since currently already 3 commits are not signed anyway
1. Resign the commit with your own key

**Comment by kkoenen** [comment]
Hm. Apparently I'm making some sort of mistake, as I cannot push to the original commit (e09d549aa0569d7b863566ea38e5ef53d46add1). Permission denied. Not sure what's wrong now. I pushed a signed commit with the same content. All good now, @JolandaVerhoef ?

**Pull request merged**
